name: newMainCaller # workflow name

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

env:
  TENANT_UTL: Not_used    # env example
  CONFIG_FILE: configuration.json


jobs:
  run-depoy-configuration:
    name: deploy tenant configuration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy configuration
      run: do something here
    - name: Deploy configuration
      run: |     # grant permission to execute script/Deploy.sh file
        chmod +x ./script/Deploy.sh        
        sh ./script/Deploy.sh ${{ github.workspace }}$CONFIG_FILE  > output_file.txt
        echo "::set-output name=file_path::${{ github.workspace }}/output_file.txt" 
      working-directory: "./reltio" 
    - name: Run test script2
      run: |                                  
        sh ./script/RunTestScripts.sh ${{ github.workspace }}$CONFIG_FILE  > output_file.txt
        echo "::set-output name=file_path::${{ github.workspace }}/output_file.txt" 
