name: newMainCaller # workflow name

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

env:
  TENANT_UTL: Not_used    # env example
  CONFIG_FILE: configuration.json


jobs:
  run-depoy-configuration:
    name: deploy tenant configuration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy configuration
      run: |     # grant permission to execute script/Deploy.sh file
        chmod +x ./Deploy.sh 
        pwd
        ls -l 
        curl --location --request POST 'https://auth02.reltio.com/oauth/token?username=soumen%402pirad.com&password=Passw0rd%40Sou&grant_type=password' --header 'Authorization: Basic cmVsdGlvX3VpOm1ha2l0YQ=='
      working-directory: "./script" 
    - name: Run test scripts
      run: |                                  
        sh RunTestScripts.sh ${{ github.workspace }}$CONFIG_FILE  > output_file.txt
        echo "::set-output name=file_path::${{ github.workspace }}/output_file.txt" 
      working-directory: "./script"
