name: newMainCaller # workflow name

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

env:
  TENANT_UTL: Not_used    # env example
  CONFIG_FILE: configuration.json


jobs:
  run-depoy-configuration:
    name: deploy tenant configuration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy configuration
      run: |     # grant permission to execute script/Deploy.sh file
        chmod +x ./Deploy.sh 
        pwd
        ls -l 
        sh Deploy.sh   > output_file.txt
        cat output_file.txt
      working-directory: "./script" 
    - name: Run test scripts
      run: |                                  
        sh RunTestScripts.sh   > output_file.txt
        cat output_file.txt 
      working-directory: "./script"
